#Create a file with the .http or .rest extension.
#In the created file, use the Add Request editor shortcut link or compose the request manually.
#Click the Run button in the gutter to run the request and view the received response.
#Use the Examples editor shortcut link to explore the additional features and capabilities.
#Use the Open Log editor shortcut link to get an overview of the 50 recently executed requests and rerun any of them.

###

POST http://localhost:3000/api/auth/create
Content-Type: application/json

{
  "username": "Test",
  "email": "test@email.com",
  "password": "password"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "Test",
  "password": "password"
}

###

DELETE http://localhost:3000/api/auth/logout
Content-Type: application/json

###

POST http://localhost:3000/api/users/calendars
Content-Type: application/json

[
  1
]

###

GET http://localhost:3000/api/users/calendars

###

POST http://localhost:3000/api/calendars
Content-Type: application/json

{
  "calendar_id": 2,
  "name": "ryans calendar",
  "event_times": [1744322520000]
}

###

GET http://localhost:3000/api/calendars

###

POST http://localhost:3000/api/times
Content-Type: application/json

{
  "time": 1744322520000,
  "event_ids": [1]
}

###

GET http://localhost:3000/api/times

###

POST http://localhost:3000/api/events
Content-Type: application/json

{
  "event_id": 2,
  "name": "test EEEE",
  "description": "this is a test"
}

###

POST http://localhost:3000/api/events
Content-Type: application/json

{
  "name": "test event",
  "description": "this is a test"
}

###

GET http://localhost:3000/api/events